
CREATE DATABASE IF NOT EXISTS `adm_db` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `adm_db`;

CREATE TABLE `adm_clientes` (
  `ADM_CLI_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ADM_CLI_TIPO` VARCHAR(5) NULL DEFAULT NULL,
  `ADM_CLI_CPF_CNPJ` VARCHAR(20) NULL DEFAULT NULL,
  `ADM_CLI_NOME` VARCHAR(255) NULL DEFAULT NULL,
  `ADM_CLI_NOME_FANT` VARCHAR(255) NULL DEFAULT NULL,
  `ADM_CLI_DT_CAD` DATETIME NULL DEFAULT NULL,
  `ADM_CLI_DT_NASC` DATETIME NULL DEFAULT NULL,
  `ADM_CLI_RG` VARCHAR(50) NULL DEFAULT NULL,
  `ADM_CLI_GRUPO_ID` INT(11) NULL DEFAULT NULL,
  `ADM_CLI_FONE_RES` VARCHAR(20) NULL DEFAULT NULL,
  `ADM_CLI_FONE_CEL1` VARCHAR(20) NULL DEFAULT NULL,
  `ADM_CLI_FONE_CEL2` VARCHAR(20) NULL DEFAULT NULL,
  `ADM_CLI_CEP` VARCHAR(10) NULL DEFAULT NULL,
  `ADM_CLI_LOG` VARCHAR(255) NULL DEFAULT NULL,
  `ADM_CLI_LOG_CIDADE` VARCHAR(255) NULL DEFAULT NULL,
  `ADM_CLI_LOG_BAIRRO` VARCHAR(255) NULL DEFAULT NULL,
  `ADM_CLI_LOG_UF` VARCHAR(50) NULL DEFAULT NULL,
  `ADM_CLI_LOG_NUM` INT(11) NULL DEFAULT NULL,
  `ADM_CLI_LOG_COMP` VARCHAR(255) NULL DEFAULT NULL,
  `ADM_CLI_EMAIL` VARCHAR(255) NULL DEFAULT NULL,
  `ADM_CLI_OBS` MEDIUMTEXT NULL,
  `ADM_CLI_EXCLUIDO` CHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`ADM_CLI_ID`)
)
COLLATE='latin1_general_ci'
ENGINE=InnoDB
;
